name: Continuos Integrations on Pull Request

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
    
      - name: Set up Python ${{ matrix.python-versio }}
        uses: actions/setup-python@v3
        with:
          python-version: 3.12.2
      
      - name: Install dependecies
        run: |
          pip install -r requirements.txt

      - name: Run Test
        id: run-tests
        run: |
          pytest -vv
        continue-on-error: false

      - name: Set test status
        if: success()
        id: test-status
        run: echo "tests_passed=true" >> $GITHUB_ENV
