name: Continous Integrations
on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
    
      - name: Intall Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.2'
      
      - name: Run Test
        run: py -m pytest -vv