name: Tag Push Handler

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
    
      - name: Set up Python 3.12.2
        uses: actions/setup-python@v3
        with:
          python-version: 3.12.2 
      
      - name: Install dependecies
        run: |
          pip install -r requirements.txt
      
      - name: Run Test
        id: run-tests
        run: |
          pytest -vv --continue-on-errors
        

      - name: Set test status
        if: success()
        id: test-status
        run: echo "tests_passed=true" >> $GITHUB_ENV
